### ISSUE TITLE
AmazonIdentityManagementException when deploying a Lambda function

### ISSUE THREAD

**Issue by jmngpt** [aws/aws-toolkit-eclipse#97] opened 2018-01-03 10:56 UTC
I installed the AWS Toolkit for Eclipse and created a Lambda project without issues, but I can't deploy my code from Eclipse directly to a Lambda function on AWS. All my AWS services are on the us-east/virginia region.

Whem I select "upload function to aws lambda", on the "Select Target Lambda function" screen, I can see and select an existing function (which resides on us-east/virginia). 

On the next screen ("Function Configuration"), I get the following error: "Failed to load iam role in US East (Virginia): com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: Credential should be scoped to a valid region, not 'us-west-2'. (Service: AmazonIdentityManagement; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: <redacted>)."

I get the same error if I randomly change the "Lambda Handler and Target Region" on the "upload function to aws lambda" screen.

Is there a configuration problem with my setup? What is causing this error?

**Comment by jmngpt** [comment] 2018-01-03 15:19
Solved by seting the default region to US East (Virginia) in Eclipse preferences: Window -> Preferences -> AWS Toolkit -> Regions.

**Comment by zhangzhx** [comment] 2018-01-05 00:17
Same issue to https://github.com/aws/aws-toolkit-eclipse/issues/94. The fix will be included in the next release.

**Comment by zhangzhx** [comment] 2018-01-05 00:59
This fix has been included in the [release](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201801042359). Thanks for the request.

**Closed by zhangzhx** 2018-01-05 00:59 UTC

**Comment by Tsaeeds** [comment] 2018-07-18 21:30
I am also having the same issue even after changing the region to US East (Virginia) here: Window -> Preferences -> AWS Toolkit -> Regions. Can you help me find out what's the problem this time?

**Comment by YugandharaP** [comment] 2018-11-05 06:29
I am also facing same issue  even after changing the region to US East (Virginia)

**Comment by prabhakar747** [comment] 2019-02-10 03:39
Am also facing same issue even after chaning to US EAST/N Virginia

**Comment by zhangzhx** [comment] 2019-02-13 18:28
Hi, @Tsaeeds @YugandharaP @prabhakar747 ,

Still couldn't reproduce this issue. Are you using the latest version of the Toolkit? You can find out the plugin version through **Eclipse** -> **About Eclipse** -> **Installation Details** -> **Installed Software** -> **Filter by typing AWS**.
