### ISSUE TITLE
AWS Eclipse Toolkit does not list Lambda with AWS Runtime Java 11

### ISSUE THREAD

**Issue by mihai1git** [aws/aws-toolkit-eclipse#255] opened 2022-12-27 15:39 UTC
Hello,

I'm using AWS Eclipse Toolkit to build Lambda packages and deploy them in AWS Lambda service. 

The option "Upload function to AWS Lambda", does not list (in drop-down "Choose an existing lambda function") all Lambda functions from the AWS account and zone, when the AWS Runtime of the Lambda is Java 11 (Correto). When the AWS Runtime is Java 1.8, the Lambda appears in the Eclipse drop-down (please see attachments). 

![existingLambdaMissing](https://user-images.githubusercontent.com/50200101/209688557-127035e9-6102-4d08-9697-6521971caa35.jpg)
![existingLambdaPresent](https://user-images.githubusercontent.com/50200101/209688559-b3ee9f05-7393-4df9-869a-3cab835f13c5.jpg)

The Eclipse IDE (Version: 2018-12 (4.10.0) Build id: 20181214-0600) is running using Java 1.8, while the Lambda function is compiled with Java 11.

There are some features that I need in Java 11 for this Lambda, so how could I make the deploy ?

Thank you,
Mihai

**Comment by JadenSimon** [comment] 2022-12-27 20:58
Thanks for the report!

This appears to be a duplicate of #208. To summarize, the Toolkit does not support Java 11 Lambdas. Feel free to re-open this issue if the aforementioned issue does not cover your use-case(s).

**Closed by JadenSimon** 2022-12-27 20:58 UTC
