### ISSUE TITLE
Uploading function to Lambda forces me to create a new S3 Bucket each time.

### ISSUE THREAD

**Issue by maitreya1975** [aws/aws-toolkit-eclipse#34] opened 2016-03-09 03:59 UTC
I'm using the Eclipse Plugin to upload java code to Lambda. Every time I do this, it does not pick up the existing S3 buckets but forces me to create a new bucket. This is bad since I now end up with lots of buckets, one for each time I upload a new code update.

**Comment by fulghum** [comment] 2016-03-09 16:09
Thanks for reporting this.  We'll see if we can reproduce the problem and get this fixed.  

Can you tell us a little more about your setup?  What version of Eclipse are you running?  Have you checked that you have the latest code from the AWS Eclipse update site?  Are there any interesting messages in the Error Log view when you encounter this problem in the Lambda wizard?

**Comment by zhangzhx** [comment] 2016-03-14 07:37
I run into this issue as well. After a lot of tests and investigation, it seems that it is because that the correct buckets couldn't be fetched from S3. 

Eclipse toolkit is using a thread pool of size 10 to fetch buckets in the given region. It is using a CountDownLatch to sync all the worker threads. For some reason, the CountDownLatch's count never reaches 0 which will block the bucket-fetching thread from returning the bucket array result. The related code is as below.

https://github.com/aws/aws-toolkit-eclipse/blob/master/com.amazonaws.eclipse.lambda/src/com/amazonaws/eclipse/lambda/upload/wizard/page/S3BucketUtil.java#L40

**Comment by zhangzhx** [comment] 2016-03-17 00:15
Hi, we have fixed this bug. Please update the Lambda plugin to the latest version:

AWS Lambda Plugin1.0.0.v201603160054

**Comment by zhangzhx** [comment] 2016-03-17 00:16
I'm closing this issue. Feel free to reopen it if you have further questions.

**Closed by zhangzhx** 2016-03-17 00:16 UTC
