### ISSUE TITLE
unable to upload jar file to lambda

### ISSUE THREAD

**Issue by TangallapalliBharathchandra** [aws/aws-toolkit-eclipse#173] opened 2020-03-14 09:36 UTC

**Comment by justinmk3** [comment] 2020-03-14 22:05
Is this different than one of these existing "jar" issues:
https://github.com/aws/aws-toolkit-eclipse/issues?q=is%3Aissue+jar+is%3Aopen

Looks like a duplicate of https://github.com/aws/aws-toolkit-eclipse/issues/171 .

**Closed by justinmk3** 2020-03-14 22:05 UTC
