### ISSUE TITLE
Error upload lambda function to AWS

### ISSUE THREAD

**Issue by tomshabtay** [aws/aws-toolkit-eclipse#94] opened 2017-12-28 14:44 UTC
Hello,

I was trying to write AWS Lambda function in Eclipse using this tutorial:
http://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/lambda-tutorial.html

When i tried to upload the function to aws, the dialog in eclipse showed me this error:

>Failed to load iam role in US East (Virginia): com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: Credential should be scoped to a valid region, not 'us-east-2'. (Service: AmazonIdentityManagement; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: e1a33c7c-ebd8-11e7-ab2c-af22232
c632aa4a6).

![aws-error](https://user-images.githubusercontent.com/18561434/34413564-ecb5f550-ebec-11e7-9af6-0d865c00a41f.png)

Everything else is working great, i can see S3 buckets and EC2 machines.

Thanks,
Tom

**Comment by zhangzhx** [comment] 2017-12-28 20:30
Thanks for reporting this to us. I can reproduce this issue when choosing a region other than `us-east-1`. The reason is because IAM is using a global endpoint whose signing region is always `us-east-1`.

I will submit a fix in the next release.

**Comment by tomshabtay** [comment] 2017-12-31 12:37
Thank you for the quick response! looking forward for the fix.

**Comment by zhangzhx** [comment] 2018-01-05 00:56
This fix has been included in the [release](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201801042359). Thanks for the request.

**Closed by zhangzhx** 2018-01-05 00:56 UTC
